### ISSUE TITLE
Auto-remove unused dependencies

### ISSUE THREAD

**Issue by nkbt** [ericclemmons/npm-install-webpack-plugin#15]
Reminds me of https://github.com/tomchentw/unused-files-webpack-plugin but for npm dependencies.

Makes sense to lock down to only ones installed by `npm-install-webpack-plugin`, so it won't remove any extras.

**Comment by ericclemmons** [comment]
Heh, I considered this but gave up on the idea.  Figured that unless _everything_ went through webpack (personally, I use Webpack for server, client, _and_ tests!), there'd be false positives.

Let me know if you can think of a bulletproof way of this plugin handling this.  From experience, I know it's not as easy as having webpack bundle everything, since it routinely breaks without a carefully crafted configuration...

**Comment by nkbt** [comment]
I think if you keep auto-installed deps listed somewhere like `.autoinstall` files, you can safely remove them afterwards. No touching any other deps though.

Opt-out if not needed. That would be quite cool for newcomers. But as soon as you settle - plugin goes away, obviously.

**Comment by nkbt** [comment]
Or it could be a section in `package.json` itself alternatively

**Comment by ericclemmons** [comment]
I agree that this would be a cool addition!  I think there are too many edge-cases to consider, _namely_ that there's no telling which dependencies may make their way into `npm run` and outside the visibility of this plugin.

In the interest of keeping this focused on rapid development, this is probably out of scope.

In practice, I think other projects are probably better suited for auditing dependencies _after_ coding is complete:

- https://www.npmjs.com/package/depcheck
- https://www.npmjs.com/package/dependency-check

Thanks for the feedback!
