### ISSUE TITLE
Modules installed on parent are not seen

### ISSUE THREAD

**Issue by TCMiranda** [ericclemmons/npm-install-webpack-plugin#32]
Hey guys! Great tool thanks!

Unfortunately I have a breaking issue, that some of my development modules are defined on the parent  `package.json`, and the tool started to install them in my child module assuming they were not installed.

I didn't had the chance to check how it works, but using `require.resolve(module)` shouldn't fix this?

Thanks!!!!

**Comment by ericclemmons** [comment]
Version & example please!

There should be one `package.json` for the project in the context that webpack is running (literally, `context`, which defaults to `process.cwd()`).

It must mean that webpack is having an issue resolving it, because I'm no longer using `require.resolve`, since it's not 100% how Webpack works.

**Comment by datwheat** [comment]
webpack resolve fixes it https://webpack.github.io/docs/configuration.html#resolve-modulesdirectories

**Comment by ericclemmons** [comment]
Closing as this seems to be a misunderstanding of how the project works.

It's for installing dependencies _in the scope of the current project_ that's missing.

Let me know if I misunderstood...
